controller:
  config:
    compute-full-forwarded-for: "true"
    enable-real-ip: "true"
    log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id "$cookie_sessionid"'
    forwarded-for-header: CF-Connecting-IP
    nginx-status-ipv4-whitelist: 10.0.1.21
